default: &default
  adapter: postgresql
  encode: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: password
  host:     db
  template: template0

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  <% if Rails.env.production? %>
  username: <%= Rails.application.credentials.pg[:username] %>
  password: <%= Rails.application.credentials.pg[:password] %>
  <% end %>
  database: myapp_production
