default: &default
  adapter: postgresql
  encode: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: password
  host:     <%= ENV['POSTGRES_HOST'] %>
  template: template0

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: banana
  password: Atom1012
  database: myapp_production
